### ISSUE TITLE
Recently joined

### ISSUE THREAD

**Issue by Guerre-Pablo-Agustin** [Pawpal-community/Infinify#7]

**Comment by Marco90v** [comment]
Desarrolle e implemente el componente **RecentlyJoined.tsx** y un servicio llamado **RecentlyApi.ts**, pensando en usarlo a futuro con un back-end, por el momento realiza solicitudes a una URL (random user generator) que retorna una "n" cantidad de personas de manera aleatoria, usa un transform para modificar los datos recuperados y convertirlos a uno parecido a la API de spotify.

![preview](https://i.imgur.com/rwEmhl7.png)
